services:
  postgres:
    image: postgres:16
    container_name: cyber_postgres
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cyber

  migrate:
    build: ./backend
    container_name: cyber_migrate
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy"
    restart: "no"
    networks:
      - cyber

  backend:
    build: ./backend
    container_name: cyber_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./uploads:/data/uploads
    networks:
      - cyber
    ports:
      - "127.0.0.1:3001:3001"

  frontend:
    build: ./frontend
    container_name: cyber_frontend
    restart: always
    env_file:
      - ./frontend/.env.production
    networks:
      - cyber
    ports:
      - "127.0.0.1:3000:3000"
volumes:
  pgdata:

networks:
  cyber:
    driver: bridge